services:
  squid:
    build: .
    container_name: squid
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./blocked_sites.txt:/etc/squid/blocked_sites.txt
    restart: unless-stopped
